export const USERS_FETCH = 'users_fetch'
export const USER_EDIT = 'user_edit'
export const USER_DELETE = 'user_delete'
export const LOGIN_AUTH = 'login_auth'
export const CHECK_AUTH = 'check_auth'
export const LOGOUT_AUTH = 'logout_auth'
